spring:
  datasource:
    druid:
      url: jdbc:mysql://bdbaq.cn:3306/redTrip
      username: root
      password: 1937dzl.
      max-active: 20
      min-idle: 8
      initial-size: 10
    tomcat:
      min-idle: 20
      max-idle: 40

  redis:
    database: 2
    host: bdbaq.cn
    port: 6379
    password: 1937dzl.
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 30
  cache:
    type: redis
    redis:
      time-to-live: 3600000
CustomCache:
  expireTime: 3600000
  preFix: Details:user-
Visit:
  expireTime: 86370000
  preFix: User:Visit-
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true


server:
  port: 10086
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


hotArticle:
  preFix: Hot:Article-
  expireTime: 30000
  RandomMin: 500
  RandomMax: 1000