spring:
  datasource:
    druid:
      url: jdbc:mysql://bdbaq.cn:3306/redTrip
      username: root
      password: 1937dzl.
  redis:
    database: 2
    host: bdbaq.cn
    port: 6379
    password: 1937dzl.
  cache:
    type: redis
    redis:
      time-to-live: 3600000


server:
  port: 10086